config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } # 當完成驗證後，回傳成功
  

  resource :cart, only: [:show, :destory] do
    collection do
      post :add, path: ':id/add' # cart/:id/add
      # post :add, path: 'add/:id' # cart/add/:id (另一種寫法)
    end
  end
  # 單數運用情境在前台使用者再看自己資料的時候，重點不在於名稱的單複數，而是在於"resource"是否是單複數
  # resources :carts
  # 複數運用情境可能在Admin想看所有使用者資料，就可使用。因複數"resources"後面會展出(:id)，單數不會

  resources :books, only: [:index, :show] do
  # 在resources中增加第九種方法，可用collection或member這兩種方法
    # collection # 網址若沒有數字時，可用collection，e.g. 列表頁、統計頁
    #   /books/list
    #   /books/world
    # member
    #   /books/2/hello
    #   /books/2/world
    member do 
      post :comment #POST /books/:id/comment, to: 'books#comment'
    end
  end
  
  resources :publishers, only: [:show]
  resources :comments, only: [:create]
  root 'books#index'
  
  namespace :admin do
    root 'books#index' # /admin/
    # get "/", to: 'book#index'
    resources :books   # /admin/books
    resources :publishers
    resources :categories
  end

  namespace :api do
    resources :books, only: [] do # 預設8個路徑都不需要了，只保留favorite
      member do
        post :favorite # /api/books/:id/favorite
      end
    end
  end

end

app/models/book.rb
class Book < ApplicationRecord
  # validations
  validates :title, presence: true
  validates :isbn, :isbn13, presence: true, uniqueness: true
  validates :list_price, :sell_price, :page_num, numericality: { greater_than: 0 }

  #relationships
  has_one_attached :cover_image
  belongs_to :publisher # 對應publisher_id
  belongs_to :category
  has_many :comments
  has_many :favorites
  has_many :users, through: :favorites

  #scopes
  scope :available, -> { where(on_sell: true).where('list_price > 0') } #lamba是一個匿名函數
  default_scope { with_attached_cover_image }
  # def self.available 因是類別方法，所以必須在前面加一個".self"
  #   where(on_sell: true) where可在類別方法使用，其實where本身也是一種類別分法
  # end

  def favorited_by?(u)
    # favorites.find_by(user: u)
    favorites.exists?(user: u)
    # exists? = select.exists?(user: u) 會回傳布林值，效能較好
  end
  
end

app/controllers/admin/books_controller.rb
# rails g controller admin/books
# app/controllers/admin/books_controller.rb

class Admin::BooksController < Admin::BaseController
  # before_action :authenticate_user! -> 移至base_controller
  before_action :find_book, only: [:show, :edit, :update, :destroy]

  # layout 'backend' -> 移至base_controller

  def index
    @books = Book.available
                 .with_attached_cover_image
                 .page(params[:page])
                 .per(3)
  end
  
  def show
  end
  
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to admin_books_path, notice: '新增成功!!!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to edit_admin_book_path(@book), notice: '更新成功'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to admin_books_path, notice: '資料已刪除'
  end

  private

  def find_book
    @book = Book.find(params[:id])
  end

  def book_params
    clean_params = params.require(:book).permit(:title, :description, :list_price, :sell_price, :page_num, :isbn, :isbn13, :cover_image, :on_sell, :published_at, :publisher_id, :category_id)
  end

  # 移至base_controller
  # def permission_check!
  #   if current_user.role != 'admin'
  #     redirect_to root_path, notice: '無法存取'
  #   end
  # end

end

app/controllers/api/books_controller.rb
class Api::BooksController < ApplicationController
  before_action :login_check!
  
  # skip_before_action :verify_authenticity_token # 避開錯誤訊息
  
  def favorite
    book = Book.find(params[:id])
    fav = Favorite.find_by(user: current_user, book: book) # 從favorite角度
    # fav = book.favorite.find_by(yser: current_user) # 從book角度
    # fav = current_user.favorites.find_by(book: book) # 從user角度
    favorited = false
    
    if fav
      fav.destory
      favorited = false
    else
      current_user.favorites.create(book: book)
      favorited = true
    end

    render json: {status: 'ok', favorited: favorited}
  end

  private

  def login_check!
    if not user_signed_in?
      head 401 #只給你head 401，沒有body
    end
  end  

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :comment]
  # before_action :find_book, expect: [:index, :new, :create] 等同於上行
  # before_action :authenticate_user!, except: [:index, :show]
  layout 'book'

  def index
    # @books = Book.where(on_sell: true).with_attached_cover_image
    # @books = Book.available.with_attached_cover_image -> 在Book Model定義available這個類別方法(book.rb)
    # @books = Book.available.with_attached_cover_image.page(1).per(3)
    @books = Book.available
                 .with_attached_cover_image
                 .page(params[:page])
                 .per(3)
    @publishers = Publisher.available
  end
  
  def show
    # find_book
    @comment = Comment.new
    @comments = @book.comments.order(id: :desc)

  end
  
  def new
  #   @book = Book.new
  end

  # def create
  #   @book = Book.new(book_params)

  #   if @book.save
  #     redirect_to root_path, notice: '新增成功!!!' -> 只能用notice or alert
  #   else
  #     render :new -> 借 new.html.erb檔案
  #     redirect_to new_book_path, notice: '新增失敗!!!'
  #   end
  # end

  # def edit
  #   find_book
  #   @book = Book.find(params[:id]) -> 業界常用
  #   @book = Book.find_by(id: params[:id])
  #   @book = Book.find_by(id: params["id"])
  #   redirect_to root_path unless @book, notice: '查無此書'

  #   begin
  #     @book = Book.find(params[:id]) 
  #   rescue
  #     redirect_to root_path, notice: '查無此書'
  #   end
    
  #   render html: params
  # end

  # def update
  #   find_book

  #   if @book.update(book_params)
  #     redirect_to edit_book_path(@book), notice: '更新成功'
  #   else
  #     render :edit
  #   end
  # end

  # def destroy
  #   find_book
  #   @book.destroy
  #   redirect_to root_path, notice: '資料已刪除'
  # end

  def comment
    # 從comment角度
    # @comment = Comment.new(comment_params, user: current_suer, book: @book)

    # 從book角度
    # @comment = @book.comments.build(comment_params)
    # @comment.user = current_suer
    @comment = @book.comments.build(comment_params)

    # 從user角度
    # @comment = current_suer.comments.build(comment_params, book: @book)

    if @comment.save
      respond_to do |format| # format也可以是其他名稱，同理下面名稱需一致
        format.js # {render 'abc'} # 呼叫JS檔，若檔案名稱也叫format，則render同檔名的.html.erb檔
        # format.html
      end
      # render js: 'alert("HI");' # 當前端也是用Rails時，才可這樣寫
      # render json: {status: 'ok'}.to_json # 標準做法，通常".to_json"會省略
      # redirect_to @book, notice: '留言成功'
    else
      render js: 'alert("發生錯誤");'
    end
  end

  private

  def find_book
    @book = Book.find(params[:id])
  end

  # Strong Parameters (從rails 4 開始引進)
  # def book_params
  #   clean_params = params.require(:book).permit(:title, :description, :list_price, :sell_price, :page_num, :isbn, :isbn13, :cover_image, :on_sell, :published_at, :publisher_id)
  # end

  def comment_params
    params.require(:comment)
          .permit(:title, :content)
          .merge(user: current_user)
  end

end

app/helpers/book_helper.rb
module BookHelper
  def cover_image_tag(book, width: 800, height: 600, dummy_img: false)
    if dummy_img 
      if book.cover_image.attached?
        generate_cover_image(book, width, height)
      else
        image_tag fake_img(width, height)
      end
    else
      generate_cover_image(book, width, height) if book.cover_image.attached?
    end
  end

  private
  def fake_img(width, height)
    "https://fakeimg.pl/#{width}x#{height}/?text=hello"
  end

  def generate_cover_image(book, width, height)
    image_tag book.cover_image.variant(resize_to_limit: [width, height])
  end
end

app/views/admin/books/_form.html.erb
<% if @book.errors.any? %>
  <div class="notification is-warning">
    <button class="delete"></button>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= javascript_pack_tag 'datepicker' %>

<%= form_for([:admin, @book]) do |form| %>

  <div class="field">
    <%= cover_image_tag @book %>
    <%= form.label :cover_image, '封面', class: 'label' %>
    <%= form.file_field :cover_image, class: 'input' %>
  </div>

  <div class="columns">
    <div class="column is-8">
      <div class="field">
        <%= form.label :title, '標題', class: 'label' %>
        <%= form.text_field :title, class: 'input' %>
      </div>
    </div>
    <div class="column is-4">
      <div class="field">
        <%= form.label :publisher_id, '出版社', class: 'label' %>
          <div class="select is-fullwidth">
            <%= form.collection_select :publisher_id, Publisher.available, :id, :name %>
            <!-- <%= form.collection_select :publisher_id, Publisher.where(online: true), :id, :name %> -->
          </div>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :description, '內容', class: 'label' %>
    <%= form.text_area :description, class: 'textarea' %>
  </div>

  <div class="columns">
  
    <div class="column">
      <div class="field">
        <%= form.label :list_price, '售價', class: 'label' %>
        <%= form.number_field :list_price, class: 'input' %>
      </div>
    </div>

    <div class="column">
      <div class="field">
        <%= form.label :sell_price, '特價', class: 'label' %>
        <%= form.number_field :sell_price, class: 'input' %>
      </div>
    </div>

    <div class="column">
      <div class="field">
        <%= form.label :page_num, '頁數', class: 'label' %>
        <%= form.number_field :page_num, class: 'input' %>
      </div>
    </div>

    <div class="column">
      <div class="field">
        <%= form.label :category_id, '分類', class: 'label' %>
          <div class="select is-fullwidth">
            <%= form.collection_select :category_id, Category.where(online: true), :id, :name %>
          </div>
      </div>
    </div>

  </div>

  <div class="columns">
    <div class="column">
      <div class="field">
        <%= form.label :isbn, 'ISBN', class: 'label' %>
        <%= form.text_field :isbn, class: 'input' %>
      </div>
    </div>
    <div class="column">
      <div class="field">
        <%= form.label :isbn13, 'ISBN-13', class: 'label' %>
        <%= form.text_field :isbn13, class: 'input' %>
      </div>
    </div>
    <div class="colum">
      <div class="field">
        <%= form.label :published_at, '發售日期', class: 'label' %>
        <%= form.text_field :published_at, class: 'input' %>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :on_sell, '是否上架', class: 'checkbox' %>
    <%= form.check_box :on_sell %>
  </div>

  <div class="field">
    <%= form.submit class: 'button is-light is-medium' %>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<h1 class="title">編輯書本<%= @book.title %></h1>

<%= render 'form', book: @book %>

app/views/admin/books/index.html.erb
<h1 class="title"><i class="fas fa-book"></i> 書本列表</h1>

<%= link_to "新增書本", new_admin_book_path, class: 'button is-primary is-middle' %>
<%= link_to "新增出版社", new_admin_publisher_path, class: 'button is-info is-middle' %>
<%= link_to "新增分類", new_admin_category_path, class: 'button is-danger is-middle' %>

<%= paginate @books %>
  
<section class="columns is-multiline">
  <% @books.each do |book| %>
    <div class="column is-4">
      <div class="card">
        <div class="card-image">
          <figure class="image">
            <%= cover_image_tag book, width: 300, height: 300, dummy_img: true %>
          </figure>
        </div>
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4"><%= link_to book.title, book_path(book) %></p>
              <p class="subtitle is-6">@johnsmith</p>
            </div>
          </div>

          <div class="content">
            <%= book.description %>
            <time><%= book.published_at %></time>
            <hr>
            <%= link_to "編輯", edit_admin_book_path(book), class: 'button is-light is-small' %>
            <%= link_to "刪除", admin_book_path(book), method: 'delete', data: {confirm: '你確定嗎???'}, class: 'button is-light is-small' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</section>

app/views/admin/books/new.html.erb
<h1 class="title">新增書本</h1>

<%= render 'form', book: @book %>

app/views/admin/books/show.html.erb
<h1>書名: <%= @book.title %></h1>